# Generated by Django 3.0.14 on 2022-05-10 06:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_auto_20220510_1214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessClient',
            new_name='UxClient',
        ),
    ]
