# Generated by Django 3.0.14 on 2022-05-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_createtests'),
    ]

    operations = [
        migrations.AddField(
            model_name='uxclient',
            name='isEmailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
