# Generated by Django 3.0.14 on 2022-07-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_uxclient_isemailverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtests',
            name='amountpaid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='createtests',
            name='cardnumber',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='createtests',
            name='cvv',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='createtests',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='createtests',
            name='expirydate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createtests',
            name='nameoncard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
