# Generated by Django 4.0 on 2022-05-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uxtester',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
