# Generated by Django 3.0.14 on 2022-06-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0003_uploadvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uxtester',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
