# Generated by Django 4.0.5 on 2022-06-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0004_auto_20220624_1027'),
        ('Tester', '0004_feedback'),
    ]

    operations = [
    ]
