# Generated by Django 3.0.14 on 2022-06-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0004_feedback'),
        ('Tester', '0004_auto_20220624_1027'),
    ]

    operations = [
    ]
