# Generated by Django 4.0.2 on 2022-07-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0005_merge_0004_auto_20220624_1027_0004_feedback'),
        ('Tester', '0005_merge_20220629_0902'),
    ]

    operations = [
    ]
