# Generated by Django 3.0.14 on 2022-07-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0005_merge_20220629_0902'),
        ('Tester', '0005_merge_0004_auto_20220624_1027_0004_feedback'),
    ]

    operations = [
    ]
