# Generated by Django 4.0.5 on 2022-07-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0006_merge_20220703_1423'),
        ('Tester', '0006_merge_20220704_0349'),
    ]

    operations = [
    ]
