# Generated by Django 3.0.14 on 2022-07-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0006_merge_20220704_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='paymentreceived',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
