# Generated by Django 3.0.14 on 2022-07-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0007_uploadvideo_paymentreceived'),
        ('Tester', '0006_merge_20220704_0349'),
        ('Tester', '0006_merge_20220703_1423'),
    ]

    operations = [
    ]
