# Generated by Django 3.0.14 on 2022-07-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0008_merge_20220704_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='feedback',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
