# Generated by Django 3.0.14 on 2022-07-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0007_merge_20220708_1507'),
        ('Tester', '0009_uploadvideo_feedback'),
    ]

    operations = [
    ]
